### ISSUE TITLE
Slow to nonn responsive media menu[BUG] (short description)

### ISSUE THREAD

**Issue by Gnjac0rp** [CopterTec/Marlin-Sovol_SV01#1]
### My Configurations

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by 0n3-70uch** [comment]
Hi, it's included. Please check the release page. You can find the ZIP files there.

**Comment by 0n3-70uch** [comment]
Please try to reformat the sd card and change the file names to short ones. It's a problem with "Alphabetical SD card sorting".
