### ISSUE TITLE
[FR] Question - is Linear Advance supported in your version of firmware?

### ISSUE THREAD

**Issue by msteele999** [CopterTec/Marlin-Sovol_SV01#12]
### Description

I'm attempting to ascertain if Linear Advance is enabled in the latest version (2.0.5.4) of Coptertec SV01 firmware. I attempted an M900 command and the mainboard replied with unknown command.

I believe my board has TMC2225 drivers - does the firmware have a way of confirming that?

Thank you for providing this firmware!

**Comment by CopterTec** [comment]
Hello, Linear Advanced is disabled because of many problems. The TMC2225 motor drivers are wrong connected to the ATMEGA.
