### ISSUE TITLE
[FR] Looking for advice on how to make modifications / contribute to the project

### ISSUE THREAD

**Issue by msteele999** [CopterTec/Marlin-Sovol_SV01#15]
Good morning,

I am fairly new to modding firmware for 3D printers. I have an SV01 and have been using your firmware for about 9 months now.

I'd like to make some tweaks to test, but I'm not sure exactly where to start. I have Visual Studio Code and have been looking over your firmware implementation.

The first thing I want to do is make sure the firmware is setup for my replacement mainboard - I have a Creality V2.2.1 now - which has TMC2208 drivers and fully supports Linear Advance.

I have been looking thru the code, and believe I may need to change the MOTHERBOARD selection in Configuration_adv.h. It looks like linear advance is actually enabled, however when I issue an M900 i get a 'Unknown Command' - so I am assuming there are other changes I need to make in the firmware.

I also see there is a pins_SOVOL_SV01.h files under mega. I guess my questions is this - is there a guide or tutorial that you could recommend on how all these parts interact? And using the 'I changed my mobo and want to use linear advance' as the motivation, how would I accomplish that? 

I think I could add to the community and your firmware version if I could complete this task.

Thank you for your time and consideration,

Best regards,

Mark

**Comment by CopterTec** [comment]
Hello, Linear Advanced is disabled because of too many problems. Please ask the people at "facebook sovol group". We cannot help heres sorry... this is only for issues and enhancements.
