### ISSUE TITLE
[FR] Which Configuration.h / Configuration_adv.h do I change?

### ISSUE THREAD

**Issue by msteele999** [CopterTec/Marlin-Sovol_SV01#18]
I am changing my hotend to an all metal E3D V6 tonight and need to change the max temp and the thermister type. I noticed there are several Configuration.h and Configuration_adv.h files in the package - do I change the one in the Marlin folder or the one in the Config/Sovol folders?

I'm not that versed with how the configuration files work in the package.

Best regards,

Mark

**Comment by msteele999** [comment]
I think I found the answer in your message threads on the main page:

For my version, you copied the Config/Sovol/myprinterversion to the /Marlin directory already - so I would modify the configuration files in the /Marlin directory for the changes to go into effect.

Is that correct?

**Comment by msteele999** [comment]
Hmmm - nope - that does not seem right.

OK - so - do *I* copy over the /Config/Sovol/myprinterversion to the /Marlin directory and then compile? I'm really sorry about all the questions - when I flashed my printer with your hex code - I didn't have to think about all this :-)

**Comment by CopterTec** [comment]
Hello, first of all. This site is for issues not for support. Now back to your question:
Just copy and replace all files from /Config/Sovol/myprinterversion to /Marlin. Thats all.

**Comment by msteele999** [comment]
Thank you. I was successful.

I am profoundly sorry for posting that question there. I won't let it
happen again.

Best regards,

Mark

**Comment by CopterTec** [comment]
Nice to hear that you were successful.

No problem... you can write but use the "edit" function please... less emails ;-).

Have a nice day
Fabi
