### ISSUE TITLE
[BUG] Blue screen when using source code

### ISSUE THREAD

**Issue by samd12** [CopterTec/Marlin-Sovol_SV01#2]
Open Marlin.ino file, compile and upload with no errors.  Stuck with blue screen on sv01 even after re-flashing multiple times.  Other firmwares load onto printer fine.

**Comment by CopterTec** [comment]
Hello, please use PlatformIO. I wrote a short description here:
https://www.coptertec.de/news/2019/marlin-2-0-for-sovol-sv01/
