### ISSUE TITLE
[BUG] only heating, does not start printing... ?

### ISSUE THREAD

**Issue by ozett** [CopterTec/Marlin-Sovol_SV01#23]
### Bug Description

i found your firmware for my new sovol s01. i printed the cube with all defaults successful, than i updated the firmware
with cura to you4 1.6.3 and after 4minutes waiting with E:heating nothing happens now...
is this normal? how long do i have to wait? in stock settings it printed after reaching the temp.

https://github.com/CopterTec/Marlin-Sovol_SV01/releases/download/1.6.3/Marlin_2.0.5.3-Sovol_SV01-1.6.3-en.hex

**Expected behavior:** [What you expect to happen]

start printing after reaching temp

**Actual behavior:** [What actually happens]

reaching temp. still showing heating....

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by ozett** [comment]
uhhh i found this: "Heats up but does not print = calibrate PID"..
now looking on your site how i do this calibration..

**Comment by ozett** [comment]
my luck, i am not the only idiot out here.. 😄 
https://www.coptertec.de/news/2019/marlin-2-0-for-sovol-sv01/?replytocom=1612

must be sowhere in the LCD menue... 
at the moment after downgrade teh SOVOL is printing...must wait for the end to try to find it...

**Comment by ozett** [comment]
no luck, at all.
i found in the LCD../configuration/auto-temp: off
switched to "on", stored all on SD-Card.

but no change. does not start printing..

do i miss something?

https://marlinfw.org/docs/features/lcd_menu.html
also here i dont see anything like: "do the PID autotune"...

any help greatly appreciated.

**Comment by CopterTec** [comment]
Hello, this is a common issue. Please run the nozzle PID autotune. Have a nice day.

**Comment by ozett** [comment]
sorry, but i am stuck.

is it a menu-option on the LCD?

i tried to find (like others in the thread).
maybe a hint, where to look?
or link to the marlin-lcd-menue structure?
or a picture? 😢  as a little help?

or do i have to do it with 3rd party-software? 
I am a little lost. the linked video has also no real instruction for that.

would appreciate it (and your firmware has some more option, looks pretty good,) ..like your copters
😸 

kind regards,
toz

**Comment by CopterTec** [comment]
Yes it's an option in the menu. Here is the menu tree:
https://marlinfw.org/docs/features/lcd_menu.html

Check out the "Tune" section. Greetings

**Comment by ozett** [comment]
i will quick jump to my sovol and do the magic.
💐 thanks for the quicker than zero-latency response.
this shades light of hope for me.

🤝

**Comment by CopterTec** [comment]
You are welcome ;-)

**Comment by ozett** [comment]
sorry to still bother,
but the printer will not start printing without autotune PID.
but the tune-menue will only be available while printing.
how should i access the tune-menue? 
![image](https://user-images.githubusercontent.com/5937811/119484375-3e994000-bd56-11eb-8a69-65fe16b514d0.png)

also marlin-page does not show "PID-Autotune".
what i am still missing? greatly appreciate another hint..

**Comment by ozett** [comment]
do it have to do autotune trough sending commands like this:

![image](https://user-images.githubusercontent.com/5937811/119485413-545b3500-bd57-11eb-862b-e78839a26ca0.png)

**Comment by CopterTec** [comment]
You can use the commands but there must be an option in the menu tree (in the deep of this menu). Sorry we sold our Sovol last year... so I can't check it now.

**Comment by ozett** [comment]
did not found on the printer-menue:

![ezgif com-gif-maker (2-76mb)](https://user-images.githubusercontent.com/5937811/119487831-23c8ca80-bd5a-11eb-92c1-caf916be38ca.gif)

i send command `M303 E0 C8 S210` with cura-console:

![image](https://user-images.githubusercontent.com/5937811/119486759-e44dae80-bd58-11eb-8cb8-0e427d9daa04.png)

**Comment by CopterTec** [comment]
There it is... Temperature > PID Autotune E1 (Extruder 1). Put in your most used temperature (for example 210°C).

**Comment by ozett** [comment]
ok. will try.
(cura command did not help)

**Comment by ozett** [comment]
for reference: change this value
![image](https://user-images.githubusercontent.com/5937811/119489316-dbaaa780-bd5b-11eb-880d-313ba04a7bb4.png)

it seems that i dont have strictly enable "Autotemp: ON" higher in this menu to get this working.
my printer now (!) starts after changing the value from 150 to 220 (for my PLA).

thousand thanks for all
💐

**Comment by CopterTec** [comment]
Thanks for your feedback. Happy printing.
