### ISSUE TITLE
[FR] bltouch probe off the bed - do you implement probe area?

### ISSUE THREAD

**Issue by ozett** [CopterTec/Marlin-Sovol_SV01#24]
### Description

i installed the bl-touch. its now probing close the the beds end on y-axis.
is there a way to configure without compiling marlin ?

### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information
![image](https://user-images.githubusercontent.com/5937811/120611029-0a0f3d80-c454-11eb-8f07-c3e14e225675.png)

https://3dprinting.stackexchange.com/questions/8153/how-to-set-z-probe-boundary-limits-in-firmware-when-using-automatic-bed-leveling/8154#8154

behind the link are some technical discussion about offsets for the probe area.
your modification seems to set the probe-offset to narrow. means probe is too near to the beds end .
any chance to change this in an easy way?

**Comment by CopterTec** [comment]
Hello, you need to compile your own firmware to change the probe area. Sorry...
