### ISSUE TITLE
[FR] saving babysteps enabled?

### ISSUE THREAD

**Issue by ozett** [CopterTec/Marlin-Sovol_SV01#25]
### Description

i am using bltouch, i set the z-offset. but i need to tune while print starts the babysteps.
i use m500 but the babysteps are lost after a cold-boot.

are the babysteps not saved in your firmware?
did you enable/disable BABYSTEP_ZPROBE_OFFSET 
https://marlinfw.org/docs/gcode/M290.html

### Feature Workflow

1. [First Action]
2. [Second Action]
3. [and so on...]

#### Additional Information

my z-probe offset is too rough , i need little babysteps to get the nozzle perfect to the bed.
is there a way to save babysteps? 
or has your firmware-mod the configuration to add the babysteps to the z-offset
(like described in marlin). - or is it missing?

**Comment by CopterTec** [comment]
Hello, please set your babysteps via the LCD screen. From the documentation:
> This behavior is means to coincide with the LCD Menu replacing “Z Babystepping” with “Babystep Z Probe Offset.” To avoid this side-effect, use M290 P0 or leave BABYSTEP_ZPROBE_OFFSET disabled.
