### ISSUE TITLE
[BUG] (seems to crash randomly and not connect to pc when plugging in)

### ISSUE THREAD

**Issue by Directory** [CopterTec/Marlin-Sovol_SV01#26]
when plugging the printer to usb i can hear windows connect but cura does not recognize a printer aka no com port shows up. and when navigating the marlin menu after a few moments it will randomly crash, reboot, show the copertech and marlin logo, sometimes a couple times, and only then will it show up as a com port to windows.

Ich entschuldige mich, wenn diese automatische deutsche Übersetzung ungenau ist.
Wenn ich den Drucker an USB anschließe, kann ich hören, dass Windows eine Verbindung herstellt, aber Cura erkennt keinen Drucker, auch wenn kein COM-Anschluss angezeigt wird. und beim Navigieren durch das Marlin-Menü stürzt es nach ein paar Augenblicken zufällig ab, startet neu, zeigt das Copertech- und Marlin-Logo manchmal ein paar Mal an und wird erst dann als COM-Port für Windows angezeigt.

**Comment by CopterTec** [comment]
Hi, seems that your bootloader is corrupt. Please reflash the bootloader via Arduino.
https://howchoo.com/ender3/ender-3-bootloader-firmware-update-marlin
