### ISSUE TITLE
[BUG] (short description) Repository TMC26XStepper missing

### ISSUE THREAD

**Issue by WebmasterPain** [CopterTec/Marlin-Sovol_SV01#27]
### Bug Description

LDF Modes: Finder ~ chain, Compatibility ~ soft
Library Manager: Installing https://github.com/trinamic/TMC26XStepper/archive/master.zip
PackageException: Got the unrecognized status code '404' when downloaded https://github.com/trinamic/TMC26XStepper/archive/master.zip:
  File "C:\Users\plonera\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 181:
    env.SConscript("$BUILD_SCRIPT")

### My Configurations

default

**Required:** Please include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by CopterTec** [comment]
Hello, the TMC26XStepper isn't in use. Please copy the correct configuration.h as described.
