### ISSUE TITLE
[FR] Neopixel/LED support

### ISSUE THREAD

**Issue by samd12** [CopterTec/Marlin-Sovol_SV01#3]
If we could use a pin from the main board for control only with Neopixel or standard leds

**Comment by CopterTec** [comment]
Hi, do you know which port can be used? I can compile a Neopixel version for you.

**Comment by samd12** [comment]
I do not know the pin number but it is 2 rows above the bltouch pins, I believe it is pin 5 as per the linked video timestamp 12:20.   https://www.youtube.com/watch?v=LEq_HFO2LYs&t=639s     There is a signal, ground and positive for each row of pins.  
![sovol board pin](https://user-images.githubusercontent.com/4117470/72099036-ba275800-32ed-11ea-829f-5de2c20bcf11.jpg)

**Comment by CopterTec** [comment]
Ok I will check it soon. Seems to be a nice feature.

**Comment by samd12** [comment]
That sounds awesome.  Look forward to it.  For most people it needs to be configured for GRB not GRBW which most code comes with.

**Comment by samd12** [comment]
You can close this.  I figured it out.

**Comment by CopterTec** [comment]
Ok. You can write a short how to... Will help many people. 

I think it's bad to implement this directly into the firmware file. To many different pixel numbers.
