### ISSUE TITLE
Marlin-Sovol_SV01-1.6.3\config 

### ISSUE THREAD

**Issue by thescreensavers** [CopterTec/Marlin-Sovol_SV01#5]
config link in readme is no longer valid.

Needs to be updated to https://github.com/MarlinFirmware/Configurations/archive/release-2.0.5.zip 

source: https://github.com/MarlinFirmware/Marlin/tree/2.0.x/config

**Comment by CopterTec** [comment]
Thanks for the information.

Closed with https://github.com/CopterTec/Marlin-Sovol_SV01/commit/2fd56ba1c13dde186bd3ae70b91385d310df128b
