### ISSUE TITLE
[BUG] G29 command for bed level

### ISSUE THREAD

**Issue by msteele999** [CopterTec/Marlin-Sovol_SV01#6]
### Bug Description

G29 command does not cause printer to do a full bed level test - the printer just chirps

### My Configurations

I am not sure how to get that. I am using OctoPrint to issue the commands to the printer and I installed 2.0.5.3 using Cura 4.6.1.

### Steps to Reproduce

1. In either Terminal (OctoPrint) or in the start gcode section of any gcode file, I issue the G29 command. The printer simply beeps but does not perform the bed test.

#### Additional Information

**Comment by CopterTec** [comment]
Hello, this firmware uses Unified Bed Leveling (UBL) and not the normal bed leveling. There is no "normal" G29 command. Please checkout this page:
https://marlinfw.org/docs/features/unified_bed_leveling.html
