### ISSUE TITLE
[FR] SKR 2.0 mini firmware

### ISSUE THREAD

**Issue by hadukennl** [CopterTec/Marlin-Sovol_SV01#8]
I have an Ender3 and SV01, I have a SKR 2.0 mini that I installed in the Ender3 that I'm trying to figure out how to compile marlin for the SV01 vs the stock board.  Is it possible to have a compiled version for that board but setup the same way as what you've done for the stock board? 

Thanks!

**Comment by CopterTec** [comment]
Hi, thats impossible at the moment. For this we need the same hardware...sorry.
