### ISSUE TITLE
[FR] Silent Mainboard V1.1.5 with TMC2208

### ISSUE THREAD

**Issue by msteele999** [CopterTec/Marlin-Sovol_SV01#9]
I am replacing my factory main board with a V2.2.1 board (https://smile.amazon.com/gp/product/B085DM75Q6/ref=ox_sc_act_title_1?smid=A3SNVVMEXOSKIB&psc=1)

Have you heard of any issues running the current firmware on this board?

Thank you!

**Comment by CopterTec** [comment]
Hi, that's a good question... Don't know if this firmware is running fine on the 2.2.1 board. Please give me a feedback.

**Comment by msteele999** [comment]
OK - we'll find out soon

**Comment by CopterTec** [comment]
Ok great. Thanks.

**Comment by msteele999** [comment]
So - the printer powers on and everything looks OK with the new board - however it looks like the BL Touch commands do not work properly. When I attempt to home Z, the probe never drops so the nozzle crashes into the bed.

I've reloaded the firmware several times with the same results.

I loaded the Sovol version of the hex file and it acts the same way - so I assume this is a problem with the board and what it expects for the BL Touch commands

**Comment by msteele999** [comment]
I found the issue - I plugged the BL Touch into D12 instead of D11 - continuing compatibility testing.

(sorry)

**Comment by CopterTec** [comment]
Hi, ok.. :-)

**Comment by msteele999** [comment]
Everything works perfectly. No issues to report.

**Comment by CopterTec** [comment]
Perfect... good news. I will add this Board to the supported devices list.

Do you flashed "SilentBoard_BLTouch" right?

**Comment by CopterTec** [comment]
I changed the README.md
https://github.com/CopterTec/Marlin-Sovol_SV01/commit/0f96e9d58afe39272c04af267bd649f78deefe94
